# Generated by Django 2.2.5 on 2019-11-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(default='2019-1-1 00:00', verbose_name='date published')),
            ],
        ),
    ]
